package com.mycompany.customersapi.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Map;

@Schema(description = "Model message and the rows returned by the SQL it generated for the question")
public record CompanyQueryResponse(
        @Schema(description = "Short human-readable message from the model about what the query returns; written without seeing any data") String message,
        @Schema(description = "SQL generated by the model and executed read-only") String sql,
        @Schema(description = "Number of rows returned (capped by the configured maximum)") int rowCount,
        @Schema(description = "Result rows, keyed by column name") List<Map<String, Object>> rows) {
}
